### ISSUE TITLE
`addClass` should accept a space separated string of class names as well as an array

### ISSUE THREAD

**Issue by mmacaula** [AmpersandJS/ampersand-dom#14]
Example:

```javascript
var InputView = require('ampersand-input-view');
var input = new InputView({
    rootElementClass : 'ui field' // this bombs
});
```

I know I can extend InputView and overwrite the `rootElementClass` prop to be an array, but it's a little verbose to do so.

**Comment by kamilogorek** [comment]
@mmacaula it's already fixed in here https://github.com/AmpersandJS/amp/tree/master/modules/add-class and it'll be propagated once we get this one done https://github.com/AmpersandJS/ampersand-dom/issues/13

**Comment by mmacaula** [comment]
Ok awesome, thanks @kamilogorek

**Comment by mmacaula** [comment]
@kamilogorek in light of amp fixing the underlying issue for the updated docs here, perhaps I'll just remove that piece and leave in documenting root element class.  Unless you can see a need for another specific 'example' customization?

**Comment by kamilogorek** [comment]
@mmacaula sounds good to me!

**Comment by mmacaula** [comment]
oops, sorry, this should be closed.
